image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-preview

tasks:
  - name: Start Airflow 3
    init: |
      export AIRFLOW_HOME=/workspace/airflow
      mkdir -p $AIRFLOW_HOME
      airflow db migrate
    command: |
      airflow api-server -p 8080 &
      sleep 5
      airflow scheduler
